/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData home_outline = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart_filled = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData user_outline = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData camera_outline = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData left_open = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData direction_outline = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData direction = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData add_a_photo = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData videocam = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData plus_1 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData bell_1 = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData cancel_outline = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData home_1 = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData attach_1 = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData bookmark_empty = const IconData(0xf097, fontFamily: _kFontFam);
  static const IconData comment_empty = const IconData(0xf0e5, fontFamily: _kFontFam);
  static const IconData bell_alt = const IconData(0xf0f3, fontFamily: _kFontFam);
  static const IconData ellipsis_vert = const IconData(0xf142, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
  static const IconData facebook_rect = const IconData(0xf301, fontFamily: _kFontFam);
}
